[package]
name = "mpw"
version = "0.0.1"
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
description = "A stateless password management solution."
readme = "README.md"
license = "MIT"

[dependencies]
rust-crypto = "0.2"
lazy_static = "0.2"
byteorder = "0.5"
rpassword = "0.2"
serde = "0.8"
serde_macros = "0.8"

[dependencies.toml]
version = "0.2"
default-features = false
features = ["serde"]

[dependencies.clap]
version = "2"
features = ["unstable", "color"]

[profile.dev]
opt-level = 2  # otherwise the tests run for too long
