[package]
name = "mpw"
version = "0.0.1"
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]

[dependencies]
rust-crypto = "0.2"
lazy_static = "0.2"
byteorder = "0.5"
rpassword = "0.2"
toml = "0.2"

[dependencies.clap]
version = "2"
features = ["unstable", "color"]

[profile.dev]
opt-level = 2  # otherwise the tests run for too long
